# Tratamento - Notebook para realizar as alterações necessárias e criar a base de dados modificada a ser usada nos demais notebooks

In [50]:
import pandas as pd

df = pd.read_csv("planilhas/dados/players_fifa22.csv", sep=";")

C:\Users\l5\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (24) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

# Tratamento de Dados

In [51]:
len(df.columns)

69

In [52]:
df.dtypes

ID                int64
Name             object
FullName         object
Age               int64
Height            int64
                  ...
GKDiving          int64
GKHandling        int64
GKKicking         int64
GKPositioning     int64
GKReflexes        int64
Length: 69, dtype: object

In [54]:
df.columns = ['ID', 'nome', 'nome_completo', 'idade', 'altura', 'peso', 'nacionalidade', 'overall', 'potencial', 'crescimento', 'total_stats', 'base_stats', 'posicoes', 'posicao_preferida', 'clube', 'valor_euro', 'salario_euro', 'passe_euro', 'posicao_clube', 'fim_contrato', 'numero_camisa', 'entrou_no_clube', 'emprestimo', 'selecao', 'posicao_selecao', 'numero_selecao', 'pe', 'dedicacao_ataque', 'dedicacao_defesa', 'velocidade_total', 'chute_total', 'ultrapassagem_total', 'drible_total', 'defesa_total', 'fisico_total', 'cruzamento', 'finalizacao', 'cabeceio', 'passe_curto', 'voleio', 'firula', 'curva', 'falta', 'passe_longo', 'controle_bola', 'aceleracao', 'explosao', 'agilidade', 'reacao', 'equilibrio', 'forca_chute', 'pulo', 'stamina', 'forca', 'chute_longo', 'agressividade', 'interceptacao', 'posicionamento', 'visao_jogo', 'penaltis', 'calma', 'marcacao', 'combate', 'carrinho', 'GK_mergulho', 'GK_maos', 'GK_chute', 'GK_posicionamento', 'GK_reflexos']

In [55]:
df.head(10)

,ID,nome,nome_completo,idade,altura,peso,nacionalidade,overall,potencial,crescimento,...,penaltis,calma,marcacao,combate,carrinho,GK_mergulho,GK_maos,GK_chute,GK_posicionamento,GK_reflexos
0,158023,L. Messi,Lionel Messi,34,170,72,Argentina,93,93,0,...,75,96,20,35,24,6,11,15,14,8
1,188545,R. Lewandowski,Robert Lewandowski,32,185,81,Poland,92,92,0,...,90,88,35,42,19,15,6,12,8,10
2,231747,K. Mbappé,Kylian Mbappé,22,182,73,France,91,95,4,...,79,88,26,34,32,13,5,7,11,6
3,200389,J. Oblak,Jan Oblak,28,188,87,Slovenia,91,93,2,...,11,68,27,12,18,87,92,78,90,90
4,192985,K. De Bruyne,Kevin De Bruyne,30,181,70,Belgium,91,91,0,...,83,89,68,65,53,15,13,5,10,13
5,190871,Neymar Jr,Neymar da Silva Santos Jr.,29,175,68,Brazil,91,91,0,...,93,93,35,32,29,9,9,15,15,11
6,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,36,187,83,Portugal,91,91,0,...,88,95,24,32,24,7,11,15,14,11
7,215914,N. Kanté,N'Golo Kanté,30,168,70,France,90,90,0,...,54,84,90,93,86,15,12,10,7,10
8,202126,H. Kane,Harry Kane,27,188,89,England,90,90,0,...,91,91,50,36,38,8,10,11,14,11
9,192448,M. ter Stegen,Marc-André ter Stegen,29,187,85,Germany,90,92,2,...,25,70,25,13,10,88,85,88,88,90

In [56]:
dup = df[df['ID'].duplicated()]
df.drop_duplicates(subset ="ID", keep = False, inplace = True)

In [57]:
df.columns

Index(['ID', 'nome', 'nome_completo', 'idade', 'altura', 'peso',
       'nacionalidade', 'overall', 'potencial', 'crescimento', 'total_stats',
       'base_stats', 'posicoes', 'posicao_preferida', 'clube', 'valor_euro',
       'salario_euro', 'passe_euro', 'posicao_clube', 'fim_contrato',
       'numero_camisa', 'entrou_no_clube', 'emprestimo', 'selecao',
       'posicao_selecao', 'numero_selecao', 'pe', 'dedicacao_ataque',
       'dedicacao_defesa', 'velocidade_total', 'chute_total',
       'ultrapassagem_total', 'drible_total', 'defesa_total', 'fisico_total',
       'cruzamento', 'finalizacao', 'cabeceio', 'passe_curto', 'voleio',
       'firula', 'curva', 'falta', 'passe_longo', 'controle_bola',
       'aceleracao', 'explosao', 'agilidade', 'reacao', 'equilibrio',
       'forca_chute', 'pulo', 'stamina', 'forca', 'chute_longo',
       'agressividade', 'interceptacao', 'posicionamento', 'visao_jogo',
       'penaltis', 'calma', 'marcacao', 'combate', 'carrinho', 'GK_mergulho',
       'GK_maos', 'GK_chute', 'GK_posicionamento', 'GK_reflexos'],
      dtype='object')

In [58]:
df['pe'][df['pe'] == 'Left'] = 'Esquerdo'
df['pe'][df['pe'] == 'Right'] = 'Direito'

<ipython-input-58-f7c5805d1bca>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['pe'][df['pe'] == 'Left'] = 'Esquerdo'
<ipython-input-58-f7c5805d1bca>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['pe'][df['pe'] == 'Right'] = 'Direito'

In [59]:
df['dedicacao_ataque'][df['dedicacao_ataque'] == 'Low'] = 'Baixa'
df['dedicacao_defesa'][df['dedicacao_defesa'] == 'Low'] = 'Baixa'
df['dedicacao_ataque'][df['dedicacao_ataque'] == 'Medium'] = 'Média'
df['dedicacao_defesa'][df['dedicacao_defesa'] == 'Medium'] = 'Média'
df['dedicacao_ataque'][df['dedicacao_ataque'] == 'High'] = 'Alta'
df['dedicacao_defesa'][df['dedicacao_defesa'] == 'High'] = 'Alta'

<ipython-input-59-6160ddad0f4a>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['dedicacao_ataque'][df['dedicacao_ataque'] == 'Low'] = 'Baixa'
<ipython-input-59-6160ddad0f4a>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['dedicacao_defesa'][df['dedicacao_defesa'] == 'Low'] = 'Baixa'
<ipython-input-59-6160ddad0f4a>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['dedicacao_ataque'][df['dedicacao_ataque'] == 'Medium'] = 'Média'
<ipython-input-59-6160ddad0f4a>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['dedicacao_defesa'][df['dedicacao_defesa'] == 'Medium'] = 'Média'
<ipython-input-59-6160ddad0f4a>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['dedicacao_ataque'][df['dedicacao_ataque'] == 'High'] = 'Alta'
<ipython-input-59-6160ddad0f4a>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['dedicacao_defesa'][df['dedicacao_defesa'] == 'High'] = 'Alta'

In [60]:
df['selecao'][df['selecao'] == 'Not in team'] = 'Fora'

<ipython-input-60-cc676a1ae46c>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['selecao'][df['selecao'] == 'Not in team'] = 'Fora'

In [61]:
df.head(10)

,ID,nome,nome_completo,idade,altura,peso,nacionalidade,overall,potencial,crescimento,...,penaltis,calma,marcacao,combate,carrinho,GK_mergulho,GK_maos,GK_chute,GK_posicionamento,GK_reflexos
0,158023,L. Messi,Lionel Messi,34,170,72,Argentina,93,93,0,...,75,96,20,35,24,6,11,15,14,8
1,188545,R. Lewandowski,Robert Lewandowski,32,185,81,Poland,92,92,0,...,90,88,35,42,19,15,6,12,8,10
2,231747,K. Mbappé,Kylian Mbappé,22,182,73,France,91,95,4,...,79,88,26,34,32,13,5,7,11,6
3,200389,J. Oblak,Jan Oblak,28,188,87,Slovenia,91,93,2,...,11,68,27,12,18,87,92,78,90,90
4,192985,K. De Bruyne,Kevin De Bruyne,30,181,70,Belgium,91,91,0,...,83,89,68,65,53,15,13,5,10,13
5,190871,Neymar Jr,Neymar da Silva Santos Jr.,29,175,68,Brazil,91,91,0,...,93,93,35,32,29,9,9,15,15,11
6,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,36,187,83,Portugal,91,91,0,...,88,95,24,32,24,7,11,15,14,11
7,215914,N. Kanté,N'Golo Kanté,30,168,70,France,90,90,0,...,54,84,90,93,86,15,12,10,7,10
8,202126,H. Kane,Harry Kane,27,188,89,England,90,90,0,...,91,91,50,36,38,8,10,11,14,11
9,192448,M. ter Stegen,Marc-André ter Stegen,29,187,85,Germany,90,92,2,...,25,70,25,13,10,88,85,88,88,90

In [62]:
df.to_csv('planilhas/dados/base_jogadores.csv', sep=';', encoding='utf-8-sig')